### ISSUE TITLE
v0.5.0 build test output -- misc errors

### ISSUE THREAD

**Issue by darkblue-b** [stac-utils/pystac#143]
Python 3.8.2 (default, Apr 27 2020, 15:53:34)   [GCC 9.3.0]
Ubuntu Linux Focal 20.04 LTS
[tmp_buildtest_050.txt](https://github.com/azavea/pystac/files/5081860/tmp_buildtest_050.txt)

**Comment by lossyrob** [comment]
Thanks for the issue!

Tested this through docker, seems like the method for running unit tests you are using are causing the errors. When running 

```
> python -m unittest discover tests
```

on a fresh clone I don't see the errors you listed (though I am getting a strange `socket.gaierror: [Errno -3] Temporary failure in name resolution` intermittently)

When running as you are with

```
> python setup.py test
```

I am seeing those errors. I'm not sure what the differences in the two test running environments are that is causing this issue; this is something we can look into, though because unit test run successfully with the intended usage I would consider this lower priority.

**Comment by darkblue-b** [comment]
ah - confirm clean run of  `python3 -m unittest discover tests`
install looks like this:
[tmp_pystac_install.txt](https://github.com/azavea/pystac/files/5087949/tmp_pystac_install.txt)

**Comment by duckontheweb** [comment]
I believe using `python setup.py test` to run tests is discouraged now and it seems like the tests run successfully using the recommended method, so I'm closing this.
