### ISSUE TITLE
Rename develop to main; remove master

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#280]
The PySTAC release route through branches __should__ got develop -> master -> release branch -> tag. As seen in https://github.com/stac-utils/pystac/pull/279, the merge into master often gets skipped because it's not utilized nor valuable IMO.

I suggest renaming develop to main, and removing master, so that the new release route would go:

- PRs go into main
- Release merge main into the release branch
- Release branch is tagged for the final release.

**Comment by matthewhanson** [comment]
This does seem to be the preferred way I see repos moving to.  I've gotten so used to the whole develop branch, then master as the last release, but have come to realize as you said, it doesn't seem to offer much benefit, since releases are tagged anyway. 

What is the purpose of the release branch though over just tagging main?  It looks like there is a branch for each minor release, is that to make backports easier?

**Comment by lossyrob** [comment]
Exactly, in especially since PySTAC is tied to producing specific STAC versions, if there's a fix we want to backport to an earlier release to make it work with users who are producing an earlier version of STAC, backporting becomes more straightforward.

**Comment by lossyrob** [comment]
__Note__: We are doing this now. If something is broken because of this change, please let us know!

**Comment by duckontheweb** [comment]
@lossyrob Looks like the CI didn't catch up to the branch name change, I can fix that in a PR.

**Comment by lossyrob** [comment]
Ah, yep that would be good!
