### ISSUE TITLE
Normalize URLs and set link types for newly added entities

### ISSUE THREAD

**Issue by matthewhanson** [stac-utils/pystac#284]
When you save a catalog it walks the tree and saves only those objects which are resolved...i.e., they are stored in memory. Which makes sense, no need to read the file in only to save it again.

However, when calling `normalize_hrefs` or `normalize_and_save`, all links are resolved and function mutates the entire tree.

This makes updates to a catalog difficult. If I have an existing catalog and add subcatalogs/items to it, it's hard to save those. I need to use `save_object`, but then have to include the code for generating the proper new self hrefs.  Also, when combined with `generate_subcatalogs` this becomes pretty tricky and I'm still trying to figure out the best way to do it.  I kept having trouble trying to set the self hrefs and link type to relative on a set of subcatalogs.

It seems like if I add a new entity to an existing catalog, part of that add should be to set the self_href, and the link type that points to it (relative or absolute), so that I can then later call just the `save` function on my catalog.   Since the only resolved item links are the new items I added this efficiently saves just the newly added items and ignores everything else. 

Somewhat related to this is would be nice to be able to easily "unresolve" entities, which would allow me to save periodically - I could save the catalog, add some items, save again, add more items, etc.

**Comment by matthewhanson** [comment]
The description above conflates a few issues so to keep this focused on the normalization of URLs for STAC Objects in a catalog.

When you normalize hrefs it resolves all [`children`](https://github.com/stac-utils/pystac/blob/5a492ca37ef6d8b0b2ea10db35150e72a709a398/pystac/catalog.py#L499) and [`items`](https://github.com/stac-utils/pystac/blob/5a492ca37ef6d8b0b2ea10db35150e72a709a398/pystac/catalog.py#L487) over the whole tree (or at least the branch of the tree you are own). This is unnecessary and can become a problem when an existing catalog is large and only a few items are added.

The self link for all added objects should automatically be set in the [`add_child`](https://github.com/stac-utils/pystac/blob/5a492ca37ef6d8b0b2ea10db35150e72a709a398/pystac/catalog.py#L151) and [`add_item`](https://github.com/stac-utils/pystac/blob/5a492ca37ef6d8b0b2ea10db35150e72a709a398/pystac/catalog.py#L180) functions. An existing catalog already uses the same base URL, accessible via the root catalog.

**Comment by matthewhanson** [comment]
@lossyrob 
I think I might be missing something here, probably something with the caching, but I'm wondering why normalization needs to walk the catalog at all.

What if, internally, all hierarchical links were represented as relative links. The base URL would be set on the root catalog (the dirname of the self link, empty string if SELF_CONTAINED).

When saving the catalog any Object will use what the root catalog specifies: the base URL and if hierarchical links should be relative or absolute. If you want to rewrite the entire catalog of course you'd need to walk through the tree, but there could be "save_all" function or similar that resolves all links and saves them.

The advantage here is that newly added items and children will have links added to them as relative, but when you save them if the catalog is an ABSOLUTE_PUBLISHED, that's when it would serialize the full URL.

**Comment by l0b0** [comment]
Is there anything the [Geostore](https://github.com/linz/geostore) team can do to help? We're going to be saving on the order of millions of metadata files in AWS S3 in the medium term. Each of them is (directly or indirectly) linked to a collection, all of which are linked to a top-level catalogue. We're starting to run into issues which I believe are caused by unnecessary traversal during `normalize_hrefs`:

- Adding/updating a collection results in processing every metadata file recursively from the top-level catalogue, so adding new datasets is taking longer every time. Would it be OK to change `normalize_hrefs` to not traverse parent/root links? Then we could simply run it on the new collection to normalise the relevant URLs.
- It seems like `normalize_hrefs` calls `write_text` for every metadata file, regardless of whether it was changed. We're using S3 file versioning, and S3 creates a new file version every time we write to a file, *regardless of whether the file contents changed.* Would it be OK to change `normalize_hrefs` to only `write_text` if any of the URLs changed?
