### ISSUE TITLE
Implement RequiredPropertyMissing exception where appropriate

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#315]
#309 implements an exception that raises when a required property is missing, using the `repr` of an object in the message to give users as much detail as possible to identify where the error is. This issue will apply after that PR is merged, and the goal of the issue is to implement throwing this exception (normally via the `get_required` utility method) where appropriate and ensuring that object `repr`s give details for any object that is throwing this exception.

**Comment by duckontheweb** [comment]
@lossyrob My sense is that this would represent a breaking change since many of these cases currently return `None`, but would raise and exception after applying this change. If that's the case it might be good to get this in under an RC1 release, but if it's not breaking we could probably release without it.
