### ISSUE TITLE
Updating validation

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/pystac#317]
Validation in pystac needs to be updated for versions 1.0.0-rc.1, rc.2, and rc.3. Would it be worth incorporating stac-validator? https://pypi.org/project/stac-validator/ If there's something missing in stac-validator that you would like to see we could try to incorporate those changes so that it could be more useful to you.

**Comment by lossyrob** [comment]
Validation should be updated with #309 . However any niceties or additional features/tests from stac-validator that can be pushed upstream would be appreciated!

**Comment by gadomski** [comment]
**stac-validator** is functioning as a standalone project, with dependencies (specifically click) that we wouldn't want to bring into PySTAC at this time. Building a similar validator to compliment [JsonSchemaSTACValidator](https://pystac.readthedocs.io/en/stable/api/validation/stac_validator.html#pystac.validation.stac_validator.JsonSchemaSTACValidator) would be nice, but I don't believe this issue is necessary to track that. Closing as not planned.
