### ISSUE TITLE
Tests and documentation for Datacube extension

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#324]
As part of #309 the Datacube extension was implemented (closing #30). There's testing and documentation left to do on this extension that should go in before the 1.0 release.

**Comment by duckontheweb** [comment]
Moving this out to 1.3.0 release since I won't have time to work on it for 1.2.0

**Comment by duckontheweb** [comment]
Moving this to the next release.

**Comment by guidorice** [comment]
I am in process of adding more unit tests to `pystac/extensions/datacube.py`, but it occurs to me that `Dimension` takes a dict in it's constructor, so also also should have `create` and `apply`, same as in https://github.com/stac-utils/pystac/issues/576 .

I think it might turn into a bit of a refactor of some of the datacube classes, because `from_dict` [here](https://github.com/stac-utils/pystac/blob/a19365b4f3431b2b4de27d6a853bf135e9270007/pystac/extensions/datacube.py) seems awkward being defined in the Abstract Base Class. 

Instead, `from_dict`, `create` and `apply` could be implemented by the concrete subclasses. Let me know if any opinions pro or co- I am not experienced using the ABC package.

cc @duckontheweb
