### ISSUE TITLE
Update 0.8.0 extension schemas for validation

### ISSUE THREAD

**Issue by jonhealy1** [stac-utils/pystac#335]
When trying to validate some 0.8.0 stac items I get this error: 

KeyError: 'https://raw.githubusercontent.com/radiantearth/stac-spec/v0.8.0/extensions/eo/json-schema/stac-extension-eo.json'

It doesn't seem to be an active link but I don't know why it would be a key error?

**Comment by pjhartzell** [comment]
This is tough to answer without the pystac version that spawned the error and a sample Item. I checked out v0.3.0 of pystac and grabbed a v0.8.0 Item that also uses the `eo` extension (`tests/data-files/eo/eo-landsat-example.json`). It validates successfully with the latest version of pystac (1.6.1)

```
import pystac
import json

href = "landsat-0.8.0.json"

# This validates. Note that from_file() converts the Item to STAC v1.0.0.
item = pystac.Item.from_file(href)
item.validate()

# This also validates. In this case there is no conversion. The Item dictionary retains its original v0.8.0 structure.
with open(href, "r") as f:
    item_dict = json.load(f)
    pystac.validation.validate_dict(item_dict)
```

Perhaps related to the incorrect schema URL? The correct URL ends with `.../schema.json`, not `.../stac-extension-eo.json`. But I don't see where the URL is used as a key.

Since a good faith attempt to replicate the problem does not produce an error, should we close this issue?

**Comment by gadomski** [comment]
> Since a good faith attempt to replicate the problem does not produce an error, should we close this issue?

Yup. @jonhealy1 please re-open w/ more information about the problem if this is still and issue from your side.
