### ISSUE TITLE
Support for 'processing' extension in pystac.Provider

### ISSUE THREAD

**Issue by scottyhq** [stac-utils/pystac#479]
Copying some discussion from gitter from @matthewhanson and @gadomski who recommended using the processing extension to add software lineage information to a STAC 

As noted https://github.com/stac-extensions/processing#item-properties-and-collection-provider-fields these extension fields are supposed to go under "providers"

But currently `pystac.Provider` only accepts "name", "roles", and "url". Aside from formally implementing support for the processing extension are there any workarounds? For example if I just want to add arbitrary fields to create the example in the extension repo: 
https://github.com/stac-extensions/processing/blob/b0dc14b3a2d0de77b0b789eb6a5ce2de6dad7771/examples/collection.json#L11-L25
```
  "providers": [
    {
      "name": "European Union/ESA/Copernicus",
      "roles": [
        "producer",
        "licensor"
      ],
      "url": "https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi",
      "processing:lineage": "Generation of Level-1C User Product",
      "processing:level": "L1C",
      "processing:facility": "Copernicus S2 Processing and Archiving Facility",
      "processing:software": {
        "IPF-S2L1C": "02.06"
      }
    },
```

**Comment by gadomski** [comment]
More generally, if extensions can add attributes to a `Provider` (or other components of STAC objects), then every component object needs to have an `extra_fields` or `properties` dictionary. `Link` supports extra attributes, but (e.g.) `Extent` and `Provider` don't.

As an aside, is there a rule for when an extension attribute should be specified at the top-level or inside of a `properties` dictionary? Does it depend on the object being extended?

**Comment by duckontheweb** [comment]
> More generally, if extensions can add attributes to a `Provider` (or other components of STAC objects), then every component object needs to have an `extra_fields` or `properties` dictionary. `Link` supports extra attributes, but (e.g.) `Extent` and `Provider` don't.

Agreed.



> is there a rule for when an extension attribute should be specified at the top-level or inside of a `properties` dictionary? Does it depend on the object being extended?

In terms of the JSON object itself, the [General Conventions section of the Extension docs](https://github.com/radiantearth/stac-spec/tree/master/extensions#general-conventions) provides some guidance on this. I think the idea is that since an Item is a GeoJSON Feature (and therefore can have a `properties` object) extra fields should go there, but for all other STAC objects they should go at the top level.

How we handle this in PySTAC might be a bit confusing, though. For `pystac.Item`, there is a distinction between `extra_fields` (which are extra top-level JSON fields) and `properties` (which are in the Item's `properties` object). However, for classes like `pystac.Link` and `pystac.Asset` we put the top-level fields into a `properties` dictionary, which could be confusing. Maybe we should change that to be called `extra_fields` to be consistent?

**Comment by gadomski** [comment]
> Maybe we should change that to be called extra_fields to be consistent?

👍🏽. To me `properties` feels "magical" because of the GeoJSON Feature thing, so (IMO) should be avoided in anything that's not a Feature.
