### ISSUE TITLE
Move CommonMetadata to use Extensions API

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#481]
CommonMetadata can be set on Assets or Items, and can have Collection summaries. This makes it most similar to an extension, even though it's not technically an extension.

CommonMetadata currently uses the old extension API when dealing with Assets. We should modify the CommonMetadata API so that it fits with the new extension API.

**Comment by duckontheweb** [comment]
Looking at the [Common Metadata Basics](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#basics) spec and it's a little unclear to me whether the `title` and `description` fields are meant to be applied to Assets as well since the spec refers only to Items (e.g. "Descriptive fields to give a basic overview of a STAC Item."). The [current `CommonMetadata` implementation](https://github.com/stac-utils/pystac/blob/a4fe4cd5f2dcde2c997c6138b2c75a963914b9d7/pystac/item.py#L40-L65) for those fields treats them differently than the remaining Common Metadata fields in that the can only be set on an `Item` and there is not optional `asset` argument to the setter.

Should we allow `title` and `description` to be set on `Asset` as well as `Item` instances?

**Comment by lossyrob** [comment]
Title and description are already on an Asset, so we coudl allow setting without a conflict. It's a little weird that you'd be able to set the title of an asset via both

```
asset.title = "foo"
CommonMetadata(asset).title = "foo"
```

but :shrug:

**Comment by duckontheweb** [comment]
> Title and description are already on an Asset, so we coudl allow setting without a conflict. It's a little weird that you'd be able to set the title of an asset via both
> 
> ```
> asset.title = "foo"
> CommonMetadata(asset).title = "foo"
> ```
> 
> but 🤷

Yeah, we don't include `datetime` in the `CommonMetadata` properties even though it is part of the Common Metadata spec, maybe for the same reason.

My vote would be to include all fields from the [Common Metadata spec](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md) as `CommonMetadata` properties even if they are already defined as instance attributes in the object itself.

**Comment by duckontheweb** [comment]
Closed by #563
