### ISSUE TITLE
EO extension can't be added to Collections

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pystac#525]
Currently the typing of the EOExtension includes `ExtensionManagementMixin[pystac.Item]`, but should be  `ExtensionManagementMixin[pystac.Collection, pystac.Item]`

Collections should list a schema URI in it's `stac_extensions` field if that Collection has summaries or assets that implement an extension (see [these docs](https://github.com/radiantearth/stac-spec/tree/master/extensions#extension-ids-in-stac_extensions))

Solving this issue should include checking for similar issues in the other extensions.

**Comment by jisantuc** [comment]
I'll grab this -- could someone with more repo powers than I have assign me?

**Comment by duckontheweb** [comment]
> I'll grab this -- could someone with more repo powers than I have assign me?

Done!

**Comment by jisantuc** [comment]
Ok so here's where I've gotten to so far, and I need a little help with Python type gymnastics:

1. `ExtensionManagementMixin` expects a single type parameter (try to pass it two -- mypy isn't happy about it)
2. extending plural monomorhpizations of `ExtensionManagementMixin` isn't allowed -- you can't for example extend both `ExtensionManagementMixin[pystac.Item]` _and_ `ExtensionManagementMixin[pystac.Collection]`
3. To deal with 2, I thought I'd just extend `ExtensionManagmentMixin[T]` for the generic type `T`, defined in `eo.py`, but `ExtensionManagementMixin` requires a subtype of `STACObject`, and `Asset` is not a subtype of `STACObject`. I think there are reasons for that -- they don't have ids or extensions or links -- but it's a hurdle for extending `ExtensionManagementMixin[T]`

So I'm a bit flummoxed. I could be flummoxed because I'm not super familiar with Python's type system though -- is there a straightforward way out of this bind?

The current state of my branch has the generic version -- https://github.com/jisantuc/pystac/blob/bugfix/js/add-collection-to-ext-mixin-where-appropriate/pystac/extensions/eo.py#L279. You can run `scripts/test` from there to see what `mypy` is mad about with the bounds (ignore the non-`eo.py` errors -- those are also my fault and need the same treatment that ends up resolving this riddle, whatever that ends up being)

**Comment by duckontheweb** [comment]
@jisantuc After looking at this a bit more, I think we might be able to solve this using `typing.Protocol` in `ExtensionsManagementMixin` instead of generics. I'm going to poke around a bit and post an example here if it seems to work.

**Comment by duckontheweb** [comment]
Yeah, so actually switching over to using `Protocol` instead of generics made everything simpler and is probably a better definition of the type we need there anyway. The changes ended up being pretty minimal, so I'll just open a PR for those.

**Comment by duckontheweb** [comment]
Actually, a problem with the Protocol approach as I implemented it is that it assumes that we can add the extension URI to anything with a `stac_extensions` property, which isn't necessarily true. Most extensions can be added to Items and Collections (for summaries), but not Catalogs, and the Item Assets Extension URI can really only be added to Collections. All of this means that we do still need some kind of check on the type of object passed to `ExtensionManagementMixin.add_to`.

@jisantuc I think the solution to your issue is to use `Union[pystac.Item, pystac.Collection]`:

```python
class EOExtension(Generic[T], PropertiesExtension, ExtensionManagementMixin[Union[pystac.Item, pystac.Collection]]):
    ...
```

That at least seems to resolve the `mypy` issues for me.
