### ISSUE TITLE
Type issues with TemporalExtent

### ISSUE THREAD

**Issue by cuttlefish** [stac-utils/pystac#586]
I'm getting errors from mypy when I try to create `TemporalExtent`s:

```
error: Argument 1 to "TemporalExtent" has incompatible type "List[List[datetime]]"; expected "Union[List[List[Optional[datetime]]], List[Optional[datetime]]]"
```

I'm creating them like this:

```
pystac.TemporalExtent([[start_datetime`, end_datetime]])
pystac.TemporalExtent([[start_datetime` or None, end_datetime or None]])
```

The first line throws the `mypy` error, the second does not. Am I missing something obvious? Is this just a fault in `mypy`?

`# type: Optional[datetime]` can also be applied to the variables.

**Comment by duckontheweb** [comment]
Based on [this issue](https://github.com/python/mypy/issues/10452) and the fact that [`List` types are invariant](https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types) it sounds like this is the expected behavior according to `mypy`, but I agree that this is a confusing user experience.

I believe that an alternate solution would be:

```python
start_datetime: List[Optional[datetime]] = ...
end_datetime: List[Optional[datetime]] = ...

pystac.TemporalExtent([[start_datetime, end_datetime]])
```

...but I haven't verified this yet.

We might be able to fix this by defining our own covariant `TypeVar` with some type [value restrictions](https://mypy.readthedocs.io/en/stable/generics.html#type-variables-with-value-restriction) so that users don't have to jump through hoops to get the typing to work.

**Comment by cuttlefish** [comment]
Ahh, I was just working on it in another repo and got the covariant warning this time.
Thanks for looking into this. I'll take a crack at it next week.
