### ISSUE TITLE
Update label extension to `1.0.1`

### ISSUE THREAD

**Issue by cuttlefish** [stac-utils/pystac#611]
The Label extension has been updated. I tried changing the version number [here](https://github.com/stac-utils/pystac/blob/c537296a25ef04c3b48ceb86016288bd49ac8904/pystac/extensions/label.py#L15) but the tests failed. I haven't had time to look into it yet.

**Comment by duckontheweb** [comment]
It looks like `jsonschema` is not able to resolve the `"#/definitions/link_fields"` reference in the updated schema. I don't see anything wrong with the schema itself, so I'm wondering if it has to do with the way we are creating and caching the `RefResolver` that gets passed in [here](https://github.com/stac-utils/pystac/blob/5ddfa839c708967227351f8c8372cb97f287fdc6/pystac/validation/stac_validator.py#L160).

I'll try to dig into this a bit more, but I probably won't have a chance until at least later tonight or tomorrow since I'm not as familiar with the validation code.

**Comment by duckontheweb** [comment]
@cuttlefish Finally had a chance to look into this some more and it turns out the JSON schema for the Label Extension v1.0.1 release was incorrect (it was still checking for the v1.0.0 schema URI in `stac_extensions`). I opened stac-extensions/label#9 and will re-publish that release once things have been merged.
