### ISSUE TITLE
Change of behavior in `str(pystac.RelType.root)`

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac#626]
In pystac 1.0, calling str on the value of an enum like `RelType.ROOT` would return the value:

```python
In [1]: import pystac

In [2]: str(pystac.RelType.ROOT)  # pystac 1.0.0
Out[2]: 'root'
```

On the latest release (1.1.0) that includes the class name.

```python
In [4]: str(pystac.RelType.ROOT)
Out[4]: 'RelType.ROOT'
```

I suspect this was changed in https://github.com/stac-utils/pystac/pull/514.

I was relying on the old behavior in https://github.com/TomAugspurger/xstac, which seems useful to me. Do we want to restore the 1.0 behavior? Or stick with the 1.1 behavior?

**Comment by lossyrob** [comment]
#514 is a change in API that we didn't catch as such - this should have technically forced a PySTAC 2.0 for semver.

I'd be in favor of reverting back to the 1.0 behavior and releasing as a bugfix version of 1.1.

@duckontheweb @l0b0 thoughts?

**Comment by l0b0** [comment]
@TomAugspurger You can get the same value by using `pystac.RelType.ROOT.value`; would that work for you?

@lossyrob Whether this should be considered an API change is interesting. The original implementation had a `__str__` implementation which was kind of pointless since the same value could be retrieved by using `.value`. Effectively there were two ways to get the literal used in STAC files, and one of those ways have been removed. I would be in favour of keeping the current behaviour but informing the users of the removal of the redundant accessor.

**Comment by TomAugspurger** [comment]
Yeah, I'm using `.value` now.

I'm no fan of semver, but this is definitely an API breaking change :) 

> underscore methods are considered "private" in Python, and should not be relied on to be stable.

There's a difference between private methods (single underscore) and "magic" or dunder methods that are part of the [Python data model](https://docs.python.org/3/reference/datamodel.html). Magic methods are meant to be used by top-level functions like `str`. So by using just public APIs `str(pystac.RelType.ROOT)` there's a change in the output.

**Comment by duckontheweb** [comment]
This seems related to #652, which is also causing breaking changes in the serialization. I'm in favor of reinstating the old behavior by overwriting the `__str__` method.
