### ISSUE TITLE
Implement `__geo_interface__`

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/pystac#786]
[`__geo_interface__`](https://gist.github.com/sgillies/2217756) is a way for Python objects to return geojson (-like) representations of themselves. Should pystac objects implement this?

This might be helpful for cases like https://github.com/stac-utils/pystac-client/issues/146, where libraries want to support a range of geojson-like objects without having to know how to convert each particular object to geojson.

**Comment by gadomski** [comment]
> Should pystac objects implement this?

Probably just `Item` since its the only `STACObject` that has a defined geometry?

**Comment by TomAugspurger** [comment]
Item is definitely the clearest, and John's suggestion for Collections make sense.

`ItemCollection` is a bit murky. There's a [comment on that gist](https://gist.github.com/sgillies/2217756?permalink_comment_id=1262671#gistcomment-1262671) about letting `__geo_interface__` include `FeatureCollection`, but it didn't seem to go anywhere.

**Comment by duckontheweb** [comment]
> `ItemCollection` is a bit murky. There's a [comment on that gist](https://gist.github.com/sgillies/2217756?permalink_comment_id=1262671#gistcomment-1262671) about letting `__geo_interface__` include `FeatureCollection`, but it didn't seem to go anywhere.

Yeah, the `ItemCollection` implementation seems murky to me. It seems like it would be most appropriate to represent it as a [`GeometryCollection`](https://github.com/MitchellPaff/stac_example/blob/0805c678d67c5284e0f6450ad7a4d2432f12dfb6/example/catalog_1/collection_1/collection.json#L7-L10) since it could conceivably contain geometries of different types. `shapely` seems to support most geometric operations (but not affine transformations) on GeometryCollections, but it doesn't seem to have the same support for FeatureCollections (shapely/shapely#770).

Maybe we should also support this for `SpatialExtent`. We could follow the same process I suggested above for Collections and then just surface that in `Collection.__geo_interface__`, too.

**Comment by philvarner** [comment]
Strongly in favor of implementing this for Item, since a STAC Item is a GeoJSON Feature with foreign members.

I'm not clear on what the value is for Collection or ItemCollection, so I think it would be better not to do that until we can really determine how it would be used.
