### ISSUE TITLE
Include stac_version in the Collection properties

### ISSUE THREAD

**Issue by Samweli** [stac-utils/pystac#806]
Request to add the `stac_version` attribute in the pystac.Collection class. The STAC Collection spec here https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md outlines the `stac_version` as a required property.

**Comment by gadomski** [comment]
`stac_version` is included in the dictionary serialization of all three STAC object types, and is set with the value of `pystac.get_stac_version()`, e.g. https://github.com/stac-utils/pystac/blob/1a1a07ef5dfd43a734da466a9f221867e7f0a809/pystac/catalog.py#L508

It is not included as an attribute of the Python objects, because PySTAC explicitly works with the latest STAC version. From [the docs](https://pystac.readthedocs.io/en/stable/concepts.html#stac-spec-version-support):

> The latest version of PySTAC supports STAC Spec 1.0.0 and will automatically update any catalogs to this version.
